dist: focal

language: go
go: "1.14"
env:
  - GO111MODULE=on
before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys F26BBE02F3C315A19BF1F791A9A25CC1CC83E839
  - echo "deb https://debs.libelektra.org/focal focal main" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install libelektra5-all
install:
  - go get -v ./...
